import { Modal } from '../ui/modal';

import PmTable from '../tables/PmTable';

import { useState } from 'react';
import { GoPlus } from 'react-icons/go';
import ScheduleBox from '../preventive-maint/ScheduleBox';

interface ModalAddAssetProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function ModalAddAsset({ isOpen, onClose }: ModalAddAssetProps) {
  const [showScheduleBox, setShowScheduleBox] = useState(false);

  return (
    <Modal isOpen={isOpen} onClose={onClose} className="fixed inset-0 w-full h-full m-0 p-0">
      <div className="no-scrollbar relative w-full  overflow-y-auto bg-white p-4 dark:bg-gray-900 lg:p-11">
        <div className="px-2 pr-14">
          <h4 className="mb-2 text-2xl font-semibold text-gray-800 dark:text-white/90">Add Part</h4>
        </div>
        <div className="w-full border-b border-[#F3F3F3]" />

        <form className="flex flex-col">
          <div className="custom-scrollbar overflow-y-auto px-2 pb-3">
            <div className="mt-7 w-full">
              <div className="w-full border-b border-[#F3F3F3] mt-4"></div>

              <div className="w-full grid grid-cols-1 md:flex items-center md:gap-8 gap-2">
                <div className="md:mt-3 mt-3 w-full">
                  <div className="flex flex-col gap-2 md:gap-2">
                    <p>Schedules</p>
                    <p>
                      Specify the details of the work order that will be generated by this
                      preventive maintenance trigger.
                    </p>
                  </div>
                  <div className="w-full grid grid-cols-1 md:flex items-center md:mt-4 mt-3 md:gap-8 gap-2 border border-[#D9D9D9] rounded-[8px] bg-white md:w-1/2 px-[24px] py-[24px]">
                    <button
                      className="w-full rounded-[8px] border border-[#D9D9D9] bg-white"
                      type="button"
                    >
                      Select existing schedule
                    </button>
                    <button
                      className="w-full rounded-[8px] border border-[#D9D9D9] bg-white relative z-20"
                      type="button"
                      onClick={() => setShowScheduleBox(!showScheduleBox)}
                    >
                      Add Schedule
                    </button>

                    {showScheduleBox && <ScheduleBox />}
                  </div>
                </div>
              </div>
              <div className="md:mt-6 mt-3 grid grid-cols-1 md:flex items-center md:justify-between">
                <div className="flex flex-col md:gap-2 gap-2">
                  <p>Assets & Locations</p>
                  <p>
                    Select Asset and Locations, assign them to the schedule, and define assignees
                    and start dates.
                  </p>
                </div>
                <div className="grid grid-cols-1 md:flex items-center md:gap-2 gap-2">
                  <button
                    className="flex items-center gap-2 md:gap-2 h-10 border border-[#D9D9D9] bg-white rounded-[8px] p-2"
                    type="button"
                  >
                    <GoPlus />
                    Add Row
                  </button>
                  <button
                    className="flex items-center gap-2 md:gap-2 h-10 border border-[#D9D9D9] bg-white rounded-[8px] p-2"
                    type="button"
                  >
                    Bulk Select Assets
                  </button>
                </div>
              </div>
              <div className="md:mt-4 mt-4">
                <PmTable />
              </div>
            </div>
            <div className="w-full flex items-center justify-end gap-2 md:gap-4 md:mt-3 mt-3">
              <button
                type="button"
                onClick={onClose}
                className="bg-white px-2 py-2 rounded border border-gray-300"
              >
                Cancel
              </button>
              <button
                className="border border-[#0C6FF9] bg-[#0C6FF9] text-white flex items-center justify-center px-2 py-2 rounded-[4px]"
                type="button"
              >
                Save Changes
              </button>
            </div>
          </div>
        </form>
      </div>
    </Modal>
  );
}
